### ISSUE TITLE
When no proxy is needed (proxy_env variable commented), the "replace" task fails

### ISSUE THREAD

**Issue by carlosedp** [ReSearchITEng/kubeadm-playbook#3]
I uncommented the "when: proxy_env is defined" line on roles/master/tasks/main.yml. This fixed the problem.

**Comment by ReSearchITEng** [comment]
should not be the case. Please check again with the latest commit.
I don't see the reason for this to fail.
For the set conditional update of admin.conf with name/FQDN: please confirm you put in the inventory the fqdn of the hosts.

**Comment by ReSearchITEng** [comment]
should be fixed by the new commits
