### ISSUE TITLE
Issue during helm sanity check 

### ISSUE THREAD

**Issue by upolymorph** [ReSearchITEng/kubeadm-playbook#34]
I am trying to use the playbook to depoly k8s on my mac with vagrant but I am always stucked during the helm sanity check testing if the tiller pod is running. I am new using kubeadm and kubernetes can you help me on what I should look for to see what is the root cause of this issue?
thanks in advance.

**Comment by ReSearchITEng** [comment]
Hello,
I suggest login to that machine and try to deploy helm manually. See what issue you get (e.g. proxy if you use one), etc.
Command to install helm:
`curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash`

**Comment by upolymorph** [comment]
Thanks for your quick answer. Here is some further infomation
running 
kubectl -n kube-system get pods
NAME                                 READY     STATUS    RESTARTS   AGE
etcd-k8sceph-01                      1/1       Running   0          1d
kube-apiserver-k8sceph-01            1/1       Running   1          1d
kube-controller-manager-k8sceph-01   1/1       Running   0          1d
kube-dns-6f4fd4bdf-2z9f9             3/3       Running   0          1d
kube-flannel-ds-ddvkt                1/1       Running   0          1d
kube-proxy-nbwmd                     1/1       Running   0          1d
kube-scheduler-k8sceph-01            1/1       Running   0          1d
tiller-deploy-59d854595c-rbflh       0/1       Pending   0          1d

helm init
$HELM_HOME has been configured at /home/vagrant/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)

tryinf the command you provided me to install helm does not give me any output

**Comment by upolymorph** [comment]
just 
curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6737  100  6737    0     0  17217      0 --:--:-- --:--:-- --:--:-- 17230

**Comment by ReSearchITEng** [comment]
This command should install helm, and it's used everywhere by the helm users.
I am using also myself very often even manually.
You may want to open an issue on the helm project if this command does not work.
