### ISSUE TITLE
Token set_fact

### ISSUE THREAD

**Issue by lukebrewerton** [ReSearchITEng/kubeadm-playbook#40]
There is an issue when setting the token fact.

`fatal: [node1.domain.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to have been in '/kubeadm-playbook/roles/node/tasks/main.yml': line 2, column 3, but may\ be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
--- 
 - set_fact: kubeadm_token=\"{{ hostvars[groups['master'][0]]['kubeadm_token'].stdout_lines[0] }}\"
   ^ here
We could be wrong, but this one looks like it might be an issue with missing quotes.  Always quote template expression brackets when they start a value. For instance:   with_items:     - {{ foo }} Should be written as:    with_items:      - "{{ foo }}"`

This is quoted as per:

`- set_fact: kubeadm_token="{{ hostvars[groups['master'][0]]['kubeadm_token'].stdout_lines[0] }}"
  when: kubeadm_master_config.token is not defined
  tags:
  - node`

**Comment by ReSearchITEng** [comment]
hey,
this was tested further in the newer version, and also some improvements added.
Please provide the logs if you still face the issue.

**Comment by lukebrewerton** [comment]
I have now pulled the `master` branch and redone my group vars from scratch. I now get an error as follows:-
```
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to have been in '/home/lbrewerton/personal_projects/kubeadm-playbook/roles/node/tasks/main.yml': line 43, column 80, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: add api section to the kubeadm_master_config (if does not exist)
  set_fact: kubeadm_master_config="{{ kubeadm_master_config | combine ( { 'api': kubeadm_master_config.api | default ({}) } ) }}"
                                                                               ^ here
```

**Comment by lukebrewerton** [comment]
This should work according to the Ansible docs for the combine filter.

**Comment by lukebrewerton** [comment]
I've found the issue. I shall fork and make a pull request

**Comment by lukebrewerton** [comment]
Pull request [44](https://github.com/ReSearchITEng/kubeadm-playbook/pull/44) submitted.

**Comment by ReSearchITEng** [comment]
I guess it's solved now. If not, please reopen.
Note: master has moved to k8s 1.12.
