### ISSUE TITLE
TASK [node : Writing JoinConfiguration

### ISSUE THREAD

**Issue by tickers** [ReSearchITEng/kubeadm-playbook#50]
TASK [node : Writing JoinConfiguration KubeProxyConfiguration and KubeletConfiguration to /etc/kubernetes/kubeadm-node.conf] ****************************************************************************************************************************************
fatal: [node01.tictoc.local]: FAILED! => {"changed": false, "checksum": "0c78762eeb9748e3ff297ea3df9ddc9cde966e63", "msg": "Destination directory /etc/kubernetes does not exist"}

**Comment by ReSearchITEng** [comment]
The code to create the folder is here, and it's being called like this:
https://github.com/ReSearchITEng/kubeadm-playbook/blob/47258357ef642b2acadb241f4c5ad8816401f761/site.yml#L51
which calls:
https://github.com/ReSearchITEng/kubeadm-playbook/blob/47258357ef642b2acadb241f4c5ad8816401f761/roles/common/tasks/kube_config.yml#L9

Can you look at the logs if that step has been executed?
I don't see a reason to have it skipped, unless some special tags combination ?

**Comment by tickers** [comment]
Cannot find anything in the logs right off. Is there a way to output the install to a log file location? 
I used -vv and thought I got some info it still is not giving me a clear picture.

**Comment by ReSearchITEng** [comment]
replicated it (when no cloud config), and solved in last commit. 
Please reopen if still happening.
