### ISSUE TITLE
unmarshaling JSON: json: cannot unmarshal string into Go value of type runtime.TypeMeta

### ISSUE THREAD

**Issue by smarty1234** [ReSearchITEng/kubeadm-playbook#52]
What could be causing the error
When I run the roles/master/tasks/main.yml
`fatal: [dockerregistry-1.xxx.com]: FAILED! => {
    "changed": true,
    "cmd": [
        "/usr/bin/kubeadm",
        "init",
        "--ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml",
        "--ignore-preflight-errors=Port-10250",
        "--config",
        "/etc/kubernetes/kubeadm-master.conf"
    ],
    "delta": "0:00:00.085650",
    "end": "2018-10-18 17:26:14.406764",
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/bin/kubeadm init   --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Port-10250 --config /etc/kubernetes/kubeadm-master.conf",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2018-10-18 17:26:14.321114",
    "stderr": "error unmarshaling JSON: json: cannot unmarshal string into Go value of type runtime.TypeMeta",
    "stderr_lines": [
        "error unmarshaling JSON: json: cannot unmarshal string into Go value of type runtime.TypeMeta"
    ],
    "stdout": "",
    "stdout_lines": []
}`

The config file generated is as follows
`cat /etc/kubernetes/kubeadm-master.conf.orig
'{u''imageRepository'': u''k8s.gcr.io'', ''controlPlaneEndpoint'': Undefined, u''kind'':
    u''ClusterConfiguration'', u''networking'': {u''podSubnet'': u''10.244.0.0/16''},
    u''clusterName'': u''dockerregistry'', u''kubernetesVersion'': u''v1.12.0'', u''apiVersion'':
    u''kubeadm.k8s.io/v1alpha3'', u''apiServerCertSANs'': [u''dockerregistry-1.xxx.com'',
    u''oamregistry-1'', u''dockerregistry-1.xxx.com''], ''etcd'': {''external'':
    {u''certFile'': u''/etc/kubernetes/pki/apiserver-etcd-client.crt'', ''endpoints'':
    [u''https://dockerregistry-1.xxx.com:2379'', u''https://dockerregistry-2.xxx.com:2379''],
    u''keyFile'': u''/etc/kubernetes/pki/apiserver-etcd-client.key'', u''caFile'':
    u''/etc/kubernetes/pki/etcd/ca.crt''}}, u''apiServerExtraArgs'': {u''service-node-port-range'':
    u''79-32767'', u''endpoint-reconciler-type'': u''lease''}}'

---
'{u''apiEndpoint'': {u''bindPort'': 6443, ''advertiseAddress'': Undefined}, u''kind'':
    u''InitConfiguration'', u''apiVersion'': u''kubeadm.k8s.io/v1alpha3'', u''nodeRegistration'':
    {u''taints'': [{u''effect'': u''NoSchedule'', u''key'': u''node-role.kubernetes.io/master''}]}}'

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clusterCIDR: 10.244.0.0/16
kind: KubeProxyConfiguration
mode: ipvs

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration`

**Comment by ReSearchITEng** [comment]
I understand you are using multi-master, right?
I noticed: in your config:
`''controlPlaneEndpoint'': Undefined`
Can you confirm custom.networking.masterha_vip is defined in your network.yml configuration ?
https://github.com/ReSearchITEng/kubeadm-playbook/blob/fea83b68b8035f946bfa138c4cad25a35d34f6a7/roles/master/tasks/main.yml#L134

**Comment by smarty1234** [comment]
I have two masters with no vip - they will be accessed via loadbalancer 

So, in general - I can't have one Virtual IP - if you say the fqdn of loadbalancer - I may have one 

yes - so if I define that with two master config - my two node etcd cluster (master and etcd are same node) fails. - I believe you do come if else comparision and don't create anything in /tmp/cert/<2nd masterid>/cets/pki - so it fails
So, I undefined that
etcd cluster works fine
now after etcd again the keepalived failed because masterha_vip was commented to fix etcd
so I created a new variable and added to   custom.networking.<new variable>

Now it fails again at master - if I enable this - again it will fail at etcd step - so I will try to create a new variable and see  

if you have any thoughts - or fixes for the above - two masters but no HA - connected via LB, please let me know.

**Comment by ReSearchITEng** [comment]
First, LB instead of VIP is in plans, but never dived into it.
Also, never tried with 2 masters. Would etcd cluster work if there is only one node?
(see https://github.com/etcd-io/etcd/issues/7906 and https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#what-is-failure-tolerance )

To your steps:
I would try to define the masterha_vip with the fqdn of LB.

Reg. etcd certs creation, these should not depend on masterha_vip variable at all. Can you put somewhere the logs with the error you get when masterha_vip is defined with yout LB fqdn?

**Comment by smarty1234** [comment]
I don't have the logs but I know why etcd clusters failed - because the file was with one IP on both nodes
cat kubeadmcfg.yaml - so etcd never came up 

As soon as I commented the vip - it created two folders as follows

xxxxxxx223:tmp mpadhi$ ls *cert*
certs.tar.gz		etcd-certs.tar.gz	master-certs.tar.gz

certs:
10.xxx.xxx.7	10.xxx.xxx.8

and certificates /root/kubeadmcfg.yaml  was transferred to both nodes properly 

So far so good: just noticed a failure here and going to put the workaround of 
`#    masterha_vip: "10.xxx.xx.8" #| default('') }}"  # keepalive needs this I think..so created the below
    masterha_vip_for_keepalive_resolve: "10.xx.xx.8" #| default('') }}"  # keepalive needs this I think..`

TASK [node : force use fqdn for master name (MasterHA case)] *  - I believe if I replace masterha_vip with masterha_vip_for_keepalive_resolve -> cluster should come up ..

etcd: needs 3 nodes and eventually I will add one later in a 3rd region.

**Comment by smarty1234** [comment]
Reg. etcd certs creation, these should not depend on masterha_vip variable at all
----
xxxxxxx223:tmp mpadhi$ ls cert
certs.tar.gz	etcd-certs.tar.gz	master-certs.tar.gz

certs:
10.xxx.xxx.7	-> this get nothing because probably my vip was master1 IP - so same IP address  with 10.xxx.xxx.8 got copied to 10.xxx.xxx.7's /root/kubeadmcfg.yaml -> so etcd failed
10.xxx.xxx.8-->primary master or master 1 - this gets content like certs/pki 

I also had to make the following work around `- name: force use vip for master name (MasterHA case)
  set_fact: master_name="{{ custom.networking.dnsDomain }}"` to replace your master_fqdn in a few places

**Comment by ReSearchITEng** [comment]
starting 1.14, this is done by kubeadm and this topic becomes irrelevant - yahoo! :)
https://github.com/ReSearchITEng/kubeadm-playbook/commit/dd0a759013eeab1b580859a9c07952524260c663
