### ISSUE TITLE
Ingress replacement + RBAC fixes

### ISSUE THREAD

**Issue by carlosedp** [ReSearchITEng/kubeadm-playbook#6]
I would recommend using Traefik ingress together with keepalived-VIP as a solution to not having a LoadBalancer.

Also, I have in my repo the fixes to the RBAC for Ingress and HELM.

Take a look in https://github.com/carlosedp/kubernetes-kit (the Readme is a guide) and my fork of your repo.

Thanks for the great work!

**Comment by ReSearchITEng** [comment]
Thanks for the suggestions.
I will add Traefik as option. Currently I am looking how to deploy a layer 4 LB. I know nginx allows it, but not by using the helm chart afaik. Do you have any exp with L4?

BTW, do you agree with this comparison: ?
https://daemonza.github.io/2017/02/13/kubernetes-nginx-ingress-controller/
```
Traefik routes to the Kubernetes service, Nginx, by pass the service and routes to the pods. This allows nginx to do sticky sessions if your application needs it.
Traefik works with multiple backends (docker, swarm, marathon, etcd, consul, kubernetes, etc. etc.) See https://docs.traefik.io/ The nginx-ingress-controller is specfic for Kubernetes, you can off course build your own Nginx reverse proxy, perhaps with OpenResty and get it to work with almost any backend, but that requires a significant time investment.
The nginx-ingress-controller can handle websockets, Traefik does not.
Traefik can do basic path manipulation by using PathPrefixStrip but cannot do more complex path rewrites like Nginx.
The nginx-ingress-controller is build on top of OpenResty (https://openresty.org). Using Lua you can easily extend Nginx capabilities and mold it to do whatever you need it to do.
```

**Comment by carlosedp** [comment]
I've never played with the Nginx ingress controller. Looks powerful, gonna read that post in detail.

I deploy Traefik because of it's simplicity and works well with my Lab needs.

Take a look on project below, seems to add a keepalived cloud provider to replace external LoadBalancers. I don't think it's L4 though.

https://github.com/munnerz/keepalived-cloud-provider

**Comment by ReSearchITEng** [comment]
Can you please point to the nginx rbac fixes in your repo?
Do you think you can push them to the nginx-ingress helm chart (https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress), so we can consume it from there?

**Comment by ReSearchITEng** [comment]
Oh, apparently it's on the way: https://github.com/kubernetes/charts/pull/1235/files

**Comment by carlosedp** [comment]
Thanks! Gonna close this now.
