### ISSUE TITLE
unknown API version for kubeadm configuration

### ISSUE THREAD

**Issue by aaleotti-unimore** [ReSearchITEng/kubeadm-playbook#61]
I've got this error while trying to install kubernetes v1.11.1 (as I have to match the latest kops supported version for another twin cluster) 

```fatal: [k8s-master1]: FAILED! => {
    "changed": true, 
    "cmd": [
        "kubeadm", 
        "init", 
        "phase", 
        "certs", 
        "etcd-ca", 
        "--config=/root/versioncfg.yaml"
    ], 
    "delta": "0:00:00.040724", 
    "end": "2019-04-05 15:10:51.397399", 
    "rc": 1, 
    "start": "2019-04-05 15:10:51.356675"
}

STDERR:

unknown API version for kubeadm configuration


MSG:

non-zero return code
```

apparently the v1.11 used the v1alpha3 API but the templates inside etcd role have that apiVersion hardcoded inside

**Comment by ReSearchITEng** [comment]
Hey,
Can you confirm you are using the branch for 1.11 ?
In general the apiversion is in the variables in the group_vars. Please point to the hard-coded part in the role to take a look.

**Comment by aaleotti-unimore** [comment]
yes you're right. i was using the master branch as it seemed it was more feature-packed than the v11.

I'll revert to branch v11 if the master is not backwards compatible for previous kubernetes versions
