### ISSUE TITLE
TASK master : Writing ClusterConfiguration and InitConfiguration fails

### ISSUE THREAD

**Issue by arush-sal** [ReSearchITEng/kubeadm-playbook#69]
What did you do:
Comment out [line 4-6](https://github.com/ReSearchITEng/kubeadm-playbook/blob/be29946006dfc9b84ee06f9554b3226ba7028922/group_vars/all/KubeletConfiguration.yml#L4-L6) in KubeletConfiguration.yaml

What you expected:
For the playbook to run without error and kubelet to be set with the specified cloud provider.

What happened:
Instead, it throws the following error:
```
The task includes an option with an undefined variable. The error was: 'kubeadm_master_config' is undefined.
...
The offending line appears to be:
- name: Writing ClusterConfiguration and InitConfiguration to /etc/kubernetes/kubeadm-master.conf
```

**Comment by ReSearchITEng** [comment]
Hello,
which release version are you using?
Please match the release with your k8s version.

**Comment by arush-sal** [comment]
I am just using the master branch with the preset/default Kubernetes version.

**Comment by ReSearchITEng** [comment]
I am not able to replicate.
Can you please see if the latest release is solving the issue you were facing?

**Comment by ReSearchITEng** [comment]
please check with the lastest version. If there is still any issue, please open again the ticket with the details.
