### ISSUE TITLE
Add/Remove Master in Existing Cluster

### ISSUE THREAD

**Issue by venomwaqar** [ReSearchITEng/kubeadm-playbook#76]
I have been trying to figure out two thing

- A feature of adding/removing a master to an exiting HA cluster
- A feature of converting an existing non-HA cluster to HA cluster

Can someone please guide if this playbook has the above features? I can't figure it out.
I have tried using with tags `etcd,master_install` but it gives me the following error

> error execution phase kubeconfig/admin: a kubeconfig file \"/etc/kubernetes/admin.conf\" exists already but has got the wrong CA cert

**Comment by ReSearchITEng** [comment]
Hi,
adding master to existing ha: Yes, this is how it's actually working: it does initially the primary-master, and then adds all those in the [secondary-masters]
the steps to add (either additional master or additional compute nodes) are:
1. prepare the hosts file and make sure: 
a. it has the [primary-master] defined
b. in the other groups it has ONLY the machines you want to add (either masters under the [secondary-masters] or nodes under [nodes] 
2. `ansible-playbook -i hosts site.yml --tags node`

**Comment by iceman91176** [comment]
Hi - i've got a bonus question ;-) We have to reinstall the primary master. How can we handle that ? General guiding (even without kubeadm-playbook) is welcome.
Thanks

**Comment by ReSearchITEng** [comment]
Kubeadm upgrade is pretty clear and simple, there is no need for much automation around it. 
Simply run in a loop across all the machines (start with masters).
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrading-control-plane-nodes
Upgrade only a version at a time (don't jump major versions).
(ideally get familiar with the process on another machine before)
PS:
The concept of "primary master" is there only part of the install flow, to denote where will be the first set of commands and where we'll run commands like: get join tokens, etc.
The cluster as such does not have/need such a concept.

**Comment by iceman91176** [comment]
@ReSearchITEng - there might be a misunderstanding. We have to reinstall the OS of our primary master. But if i get iet it right we should be able to reset/reinstall "secondary" masters with the playbook, and just move our primary master to secondary-masters group, and on of the secondaries to the primary-master group.

**Comment by ReSearchITEng** [comment]
Sorry for the misunderstanding.
If you have another machine available, I suggest add that as control plane as well (so in total you will have temporary 4 masters)
After you see all is good, remove the machine you are interested.

How to do that:
make the inventory with:
- a machine as primary master (does not matter which)
- the new machine in the secondary master section
(remove all other machines from inventory).
Now, make sure you run using the **--tags nodes**, otherwise you may reset your cluster!!!

**Comment by iceman91176** [comment]
@ReSearchITEng we went for option B with a stripped down playbook. It is important to do a proper kubeadm reset of the master you are re-installing.
