### ISSUE TITLE
DEMO video link broken

### ISSUE THREAD

**Issue by OndrejHome** [ReSearchITEng/kubeadm-playbook#77]
The link for demo - https://asciinema.org/a/Ii7NDu3eL9DsuM1fEFM9PMVTM - shows page referring to unclaimed video being removed. Could you please re-upload the video and update link or remove the link? Thank you!
~~~
This recording has been archived

All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.
~~~

**Comment by ReSearchITEng** [comment]
Thanks for the heads up!
It seems the old one was removed.
Take a look on the new one: https://github.com/ReSearchITEng/kubeadm-playbook/blob/master/README.md#demo

PS: please let us know if there are any other comments/suggestions!

**Comment by OndrejHome** [comment]
Thanks, video link now works :)
