### ISSUE TITLE
Failed to untaint single master when FQDN node name

### ISSUE THREAD

**Issue by bkmeneguello** [ReSearchITEng/kubeadm-playbook#80]
Taint fails because node is registered with FQDN but [here](https://github.com/ReSearchITEng/kubeadm-playbook/blob/b18ea1a4156c880c7e810d912cf80e9f42a07143/roles/primary-master/tasks/main.yml#L390) it uses `inventory_hostname_short`. It should respect `custom.networking.fqdn.*`

**Comment by ReSearchITEng** [comment]
Hello!,
can you please share:
0. is there a strong need to have the nodes defined in k8s with fqdn? Note that proxy for getting access to internet works just fine, without that. IMO it should be avoided, as kubeadm does not do that natively.
1. the inventory/hosts file (if all hosts are if fqdn)
2. network yml file settings (custom.networking.fqdn.* )
3. result of `kubectl get no`  (does it show with fqdn ?)

**Comment by ReSearchITEng** [comment]
please take a look at the new changes if they overcame this case

**Comment by bkmeneguello** [comment]
0. I don't want to have k8s nodes registered with FQDN, but I can accept if needed
1. (obs. *k8s* is my domain)
```
[primary-master]
node1.k8s

[secondary-masters]

[masters:children]
primary-master
secondary-masters

[nodes]
node2.k8s

[node:children]
nodes
```
2. (but `custom.networking.fqdn.always: True` does the same)
```
custom:
  networking:
    fqdn:
      always: False
      master: True
      node: False
```
3.
```
kubectl get nodes
NAME        STATUS     ROLES      AGE     VERSION
node1.k8s   Ready      master    5m53s   v1.16.2
node2.k8s   Ready      compute   5m17s   v1.16.2
```
4. enabled `set_hostname_to_inventory_hostname: True`
5.
  a. `node1`
  b. `node1.k8s`
  c. `node1.k8s`

**Comment by bkmeneguello** [comment]
I tried with master changes and it worked. The nodes are still registered with FQDN but joining worked as expected.

**Comment by ReSearchITEng** [comment]
Thanks a lot for your answers.
While the playbook has been used for both Redhat/CentOS based as well as Debian/Ubuntu based OSes, in both cases the rule was that `hostname` returns the short version (aka `hostname -s`).
While your systems follow the other practice: `hostname` returns the `hostname -f`.
It's great that you are able to work with the new changes.
For more info on these 2 practices:  https://serverfault.com/questions/331936/setting-the-hostname-fqdn-or-short-name

If there are no other complains on this, can we close the ticket?

**Comment by bkmeneguello** [comment]
Sure! And thank you very much.

**Comment by ReSearchITEng** [comment]
Thanks for your feedback!
