### ISSUE TITLE
Set NodeIP from Inventoryfile/DNS

### ISSUE THREAD

**Issue by gallexme** [ReSearchITEng/kubeadm-playbook#83]
At the Hoster Scaleway (and probably many others)  the VM's are in  a Private Network, but  may also have a public IP Assigned to them using  NAT etc
when u install kubeadm-playbook across Regions/Private Networks VM's  they cant connect to each other ( Timeout When u install Helm)

Possible Fix: using inventory_hostname in the kubelet join command --node-ip
(https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)

Testing it atm

**Comment by ReSearchITEng** [comment]
https://github.com/ReSearchITEng/kubeadm-playbook/blob/1340791221be3f46cbb7e7ecab450fa204b8f952/roles/non-primary-master/tasks/main.yml#L9

https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#NodeRegistrationOptions

**Comment by gallexme** [comment]
Huh i may been at wrong pages
i tried
{{ KubeletConfiguration combine({'nodeRegistration': {'kubeletExtraArgs': {"--node-ip={{ inventory_hostname }}"}}})  | | to_nice_yaml }}

**Comment by ReSearchITEng** [comment]
If I am not wrong, kubelet configuration will be derived from above JoinConfiguration once it joins.
Maybe replacing ansible_fqdn above with inventory_hostname would solve such cases?

**Comment by gallexme** [comment]
i already have my nodename is then node0.h0st.space
but nodeip is 10.xx , it used the ip from eth0 instead of a public ip(which is only visible externally)

**Comment by ReSearchITEng** [comment]
Suggestion: I guess the solution to your specific case is to add a post task, which updates the conf files with the external ip address instead.

**Comment by gallexme** [comment]
Question is if that a specific case that kubernetes nodes aren't in the same network?
Scaleway, digital Ocean all have only a private IP set on the network card, gce, Amazon etc probably too

**Comment by ReSearchITEng** [comment]
"Full network connectivity among all machines in the cluster. A public or private network is fine." https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

I guess it means to have the nodes in the same cluster talk directly with the default ip address defined on the host (without additional nat or similar solutions).

I suggest opening the thread on kubernetes slack channel.

**Comment by ReSearchITEng** [comment]
@gallexme, can you please update if you managed to pass / work around this?
Shall we close this topic?

**Comment by gallexme** [comment]
I still haven't found a workaround and I'm still stuck at this problem.
Also haven't gotten an answer on kubeadm slack

"Yeah, you're in territory that isn't quite "uncharted" but certainly isn't
well-trodden."
Dunno why using 2 cloud hosters is that uncharted but ok

I may could have it working with a vpn (zerotier etc) but I really wanna
avoid adding another layer of network tunnel since they both reachable over
public ipa
