### ISSUE TITLE
service-node-port-range: 79-32767 is not a sane default

### ISSUE THREAD

**Issue by bkmeneguello** [ReSearchITEng/kubeadm-playbook#85]
[ClusterConfiguration.yml#8](https://github.com/ReSearchITEng/kubeadm-playbook/blob/6aa67f9aa20c8690cc9346f4b621bd3dd9ef9e9b/group_vars/all/ClusterConfiguration.yml#L8) defines `service-node-port-range: 79-32767` but this is not a good practice because can cause conflicts with other service ports.

**Comment by ReSearchITEng** [comment]
Well, the idea is that nginx-controller has to be on 80 and 443 especially for that reason: have k8s the one to hold the web servers.
Unfortunately I am not aware of another solution to have few ranges.

**Comment by ReSearchITEng** [comment]
should anyone modify this range, the nginx controller helm chart port should be also updated in addons.yaml  
I am closing, as I don't see other better and intuitive solutin
