### ISSUE TITLE
Example of complete vars for cluster configuration

### ISSUE THREAD

**Issue by abennani31** [ReSearchITEng/kubeadm-playbook#87]
Hi,
Can you please provide a complete example with all needed variables in groups_vars/all/* for of cluster configuration: one master with deux nodes.

Thank you very much
Regards

**Comment by ReSearchITEng** [comment]
Hi,
sorry for delayed response.
The group vars are not related to number of masters or number of nodes.
Just make sure inventory (hosts) file is populated as per example.

**Comment by ReSearchITEng** [comment]
if there are any other questions, please let me know
