### ISSUE TITLE
Kubespray?

### ISSUE THREAD

**Issue by adrianog** [ReSearchITEng/kubeadm-playbook#89]
Thanks for the project.

I wanted to understand whether kubespray is a valid alternative or not?
Regards
Adriano

**Comment by ReSearchITEng** [comment]
Hi Adrian,
this project is build ground up around the modern kubeadm, making it very clean.
All the parameters for kubeadm are kept in kubeadm's native format, this way no "wheel reinvention".
Moreover, the project adds out of the box (configurable in addons.xml) things which are desired in most of the deployments: monitoring (using the modern prometheus operator), dashboard, etc.
The idea is to have a "batteries included" deployment, with best practices included by default, still allow to choose what to add/remove. 
There are many "lessons learnt" inside it, based on our experience with on-prem k8s cluster deployments.
